# Site settings
title: Writing maintainable CSS
email: pkuts@obecto.com
description: > # this means to ignore newlines until "baseurl:"
  A code style guide on how to write consistent and maintainable
  CSS across all Obecto projects
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: turbalan
github_username:  turbalan
port: 8080

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
